import { ArrowUpRight, CalendarDays, CheckCircle2, ChevronRight, Clock3, FileText, Megaphone, Search, Sparkles } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { PageHeader } from "@/components/app/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export const campaignData = [
  { id: "festive-edit", brand: "Urban Threads", title: "Festive Edit 2026", status: "Content review", due: "Sep 17, 2026", payout: "₹24,000", progress: 75, color: "from-violet-600 to-indigo-400", next: "Awaiting brand feedback" },
  { id: "everyday-radiance", brand: "Glow Theory", title: "Everyday Radiance", status: "Brief received", due: "Sep 22, 2026", payout: "₹18,000", progress: 40, color: "from-rose-500 to-orange-300", next: "Submit content concept" },
  { id: "mindful-mornings", brand: "Kind Kitchen", title: "Mindful Mornings", status: "In progress", due: "Sep 28, 2026", payout: "₹14,000", progress: 15, color: "from-emerald-500 to-teal-300", next: "Review campaign brief" },
  { id: "autumn-rituals", brand: "Luma Home", title: "Autumn Rituals", status: "Completed", due: "Sep 09, 2026", payout: "₹16,500", progress: 100, color: "from-amber-500 to-orange-300", next: "Payout processing" },
];

export function CampaignsPage() {
  return <div className="space-y-6"><PageHeader title="Campaigns" description="Manage your brand collaborations, deliverables and payouts." actions={<Button><Sparkles className="h-4 w-4" /> Discover opportunities</Button>} />
    <section className="grid gap-4 sm:grid-cols-3"><Stat label="Active campaigns" value="3" hint="Across 3 brands" /><Stat label="Pending payouts" value="₹42,000" hint="Expected this month" /><Stat label="On-time delivery" value="100%" hint="Last 6 months" /></section>
    <div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search campaigns" /></div><Button variant="outline">All statuses</Button></div>
    <div className="grid gap-4 lg:grid-cols-2">{campaignData.map((campaign) => <Card key={campaign.id} className="overflow-hidden shadow-card"><div className={`h-2 bg-gradient-to-r ${campaign.color}`} /><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">{campaign.brand}</p><h2 className="mt-1 font-display text-xl font-semibold">{campaign.title}</h2></div><Badge variant={campaign.status === "Completed" ? "secondary" : "outline"} className={campaign.status === "Content review" ? "border-primary/20 bg-primary/10 text-primary" : ""}>{campaign.status}</Badge></div><div className="mt-5 grid grid-cols-2 gap-4 rounded-xl bg-muted/50 p-3 text-sm"><div><p className="text-xs text-muted-foreground">Campaign payout</p><p className="mt-1 font-semibold">{campaign.payout}</p></div><div><p className="text-xs text-muted-foreground">Due date</p><p className="mt-1 flex items-center gap-1 font-semibold"><CalendarDays className="h-3.5 w-3.5 text-muted-foreground" />{campaign.due}</p></div></div><div className="mt-4"><div className="flex justify-between text-sm"><span className="text-muted-foreground">Campaign progress</span><span className="font-medium">{campaign.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${campaign.progress}%` }} /></div><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5" />{campaign.next}</p></div><Button asChild className="mt-5 w-full" variant="outline"><Link to="/influencer/campaigns/$campaignId" params={{ campaignId: campaign.id }}>View campaign <ChevronRight className="h-4 w-4" /></Link></Button></CardContent></Card>)}</div>
  </div>;
}
function Stat({ label, value, hint }: { label: string; value: string; hint: string }) { return <Card className="shadow-card"><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-display text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></CardContent></Card>; }

export function CampaignDetailsPage({ campaignId }: { campaignId: string }) {
  const campaign = campaignData.find((item) => item.id === campaignId) ?? campaignData[0];
  const steps = ["Campaign brief reviewed", "Content concept approved", "Create and submit deliverables", "Brand approval and payout"];
  return <div className="space-y-6"><PageHeader title={campaign.title} description={`${campaign.brand} · Collaboration workspace`} actions={<Button variant="outline" asChild><Link to="/influencer/campaigns">Back to campaigns</Link></Button>} />
    <section className="grid gap-4 sm:grid-cols-3"><Stat label="Campaign payout" value={campaign.payout} hint="Paid after approval" /><Stat label="Delivery deadline" value={campaign.due} hint="All times are local" /><Stat label="Campaign status" value={campaign.status} hint={`${campaign.progress}% complete`} /></section>
    <section className="grid gap-6 lg:grid-cols-3"><Card className="shadow-card lg:col-span-2"><CardContent className="p-6"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /><h2 className="font-display text-lg font-semibold">Campaign brief</h2></div><p className="mt-4 leading-7 text-muted-foreground">Create warm, personal content that shows how {campaign.brand} fits naturally into your everyday routine. Focus on authenticity, product value and a clear call to action.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><BriefItem label="Deliverables" value="1 Reel, 1 carousel and 3 stories" /><BriefItem label="Content window" value="September 15 – 17, 2026" /><BriefItem label="Required tags" value={`@${campaign.brand.toLowerCase().replaceAll(" ", "")} #ad`} /><BriefItem label="Usage rights" value="Organic social, 30 days" /></div></CardContent></Card><Card className="shadow-card"><CardContent className="p-6"><h2 className="font-display text-lg font-semibold">Next action</h2><p className="mt-2 text-sm text-muted-foreground">{campaign.next}</p><Button className="mt-5 w-full">Submit deliverable <ArrowUpRight className="h-4 w-4" /></Button></CardContent></Card></section>
    <Card className="shadow-card"><CardContent className="p-6"><h2 className="font-display text-lg font-semibold">Delivery timeline</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{steps.map((step, index) => <div key={step} className="relative"><span className={`grid h-8 w-8 place-items-center rounded-full ${index <= 1 ? "bg-success text-white" : "bg-muted text-muted-foreground"}`}>{index <= 1 ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</span><p className="mt-3 text-sm font-medium">{step}</p><p className="mt-1 text-xs text-muted-foreground">{index <= 1 ? "Completed" : index === 2 ? "Current step" : "Upcoming"}</p></div>)}</div></CardContent></Card>
  </div>;
}
function BriefItem({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-muted/50 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
