import { useState } from "react";
import { ArrowUpRight, BadgeIndianRupee, Copy, ExternalLink, Link2, Package, ShoppingBag, Store, TrendingUp, Users } from "lucide-react";
import { PageHeader } from "@/components/app/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Scope = "all" | "urban" | "glow" | "kind";
const scopeName: Record<Scope, string> = { all: "All stores", urban: "Urban Threads", glow: "Glow Theory", kind: "Kind Kitchen" };
const scopeData: Record<Scope, { sales: string; orders: string; earnings: string; clicks: string; conversion: string }> = {
  all: { sales: "₹1,12,450", orders: "68", earnings: "₹24,680", clicks: "3,842", conversion: "1.8%" },
  urban: { sales: "₹62,480", orders: "36", earnings: "₹13,120", clicks: "1,964", conversion: "1.8%" },
  glow: { sales: "₹31,260", orders: "19", earnings: "₹7,560", clicks: "1,102", conversion: "1.7%" },
  kind: { sales: "₹18,710", orders: "13", earnings: "₹4,000", clicks: "776", conversion: "1.7%" },
};
const products = [
  { name: "Festive Silk Co-ord Set", store: "Urban Threads", price: "₹2,499", clicks: 862, orders: 18, tone: "bg-violet-100 text-violet-600" },
  { name: "Vitamin C Glow Serum", store: "Glow Theory", price: "₹1,299", clicks: 614, orders: 12, tone: "bg-rose-100 text-rose-600" },
  { name: "Protein Breakfast Bundle", store: "Kind Kitchen", price: "₹899", clicks: 437, orders: 9, tone: "bg-teal-100 text-teal-600" },
];
const orders = [
  { id: "#UT-10482", customer: "Priya Sharma", store: "Urban Threads", total: "₹3,498", commission: "₹349", status: "Approved" },
  { id: "#GT-09114", customer: "Ananya Iyer", store: "Glow Theory", total: "₹2,598", commission: "₹260", status: "Approved" },
  { id: "#KK-03186", customer: "Vikram Rao", store: "Kind Kitchen", total: "₹1,798", commission: "₹180", status: "Pending" },
  { id: "#UT-10476", customer: "Rhea Kapoor", store: "Urban Threads", total: "₹2,499", commission: "₹250", status: "Approved" },
];

function useScope() { return useState<Scope>("all"); }
function StoreSelector({ scope, setScope }: { scope: Scope; setScope: (value: Scope) => void }) { return <Select value={scope} onValueChange={(value) => setScope(value as Scope)}><SelectTrigger className="w-full bg-card sm:w-52"><Store className="mr-2 h-4 w-4 text-muted-foreground" /><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Combined analytics</SelectItem><SelectItem value="urban">Urban Threads</SelectItem><SelectItem value="glow">Glow Theory</SelectItem><SelectItem value="kind">Kind Kitchen</SelectItem></SelectContent></Select>; }
function Metrics({ scope }: { scope: Scope }) { const data = scopeData[scope]; return <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Attributed sales" value={data.sales} icon={TrendingUp} detail="Last 30 days" /><Metric label="Orders generated" value={data.orders} icon={ShoppingBag} detail="+12.5% from last month" /><Metric label="Your earnings" value={data.earnings} icon={BadgeIndianRupee} detail="Approved + pending" /><Metric label="Link clicks" value={data.clicks} icon={Link2} detail={`${data.conversion} conversion rate`} /></section>; }
function Metric({ label, value, icon: Icon, detail }: { label: string; value: string; icon: typeof Store; detail: string }) { return <Card className="shadow-card"><CardContent className="flex items-center gap-4 p-5"><span className="grid h-10 w-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-0.5 font-display text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{detail}</p></div></CardContent></Card>; }
function filterForScope<T extends { store: string }>(rows: T[], scope: Scope) { return scope === "all" ? rows : rows.filter((row) => row.store === scopeName[scope]); }

export function StorePage() { const [scope, setScope] = useScope(); const data = scopeData[scope]; return <div className="space-y-6"><PageHeader title="My Store" description="Track the storefronts and products you share with your audience." actions={<StoreSelector scope={scope} setScope={setScope} />} /><Metrics scope={scope} /><section className="grid gap-6 xl:grid-cols-3"><Card className="shadow-card xl:col-span-2"><CardHeader className="p-5 pb-3"><CardTitle>{scope === "all" ? "Combined store performance" : `${scopeName[scope]} performance`}</CardTitle><p className="mt-1 text-sm text-muted-foreground">Sales driven by your links in the last 30 days</p></CardHeader><CardContent className="p-5 pt-2"><div className="flex h-48 items-end gap-2">{[36, 48, 42, 66, 58, 75, 69, 88, 76, 100, 84, 92].map((height, index) => <div key={index} className="flex-1 rounded-t-md bg-primary/20" style={{ height: `${height}%` }}><div className="h-full rounded-t-md bg-primary" style={{ height: `${Math.max(20, height - 18)}%` }} /></div>)}</div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Sep 01</span><span>Sep 10</span><span>Sep 20</span><span>Today</span></div></CardContent></Card><Card className="shadow-card"><CardHeader className="p-5 pb-3"><CardTitle>Store mix</CardTitle><p className="mt-1 text-sm text-muted-foreground">Where your sales come from</p></CardHeader><CardContent className="space-y-4 p-5 pt-2">{["Urban Threads", "Glow Theory", "Kind Kitchen"].map((name, index) => <div key={name}><div className="flex justify-between text-sm"><span>{name}</span><span className="font-medium">{[56, 28, 16][index]}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${[56, 28, 16][index]}%` }} /></div></div>)}</CardContent></Card></section><Card className="shadow-card"><CardHeader className="p-5 pb-3"><CardTitle>Top shared products</CardTitle><p className="mt-1 text-sm text-muted-foreground">Products your audience is responding to</p></CardHeader><CardContent className="space-y-3 p-5 pt-1">{filterForScope(products, scope).map((product) => <div key={product.name} className="flex flex-wrap items-center gap-3 rounded-xl border p-3"><span className={`grid h-10 w-10 place-items-center rounded-lg ${product.tone}`}><Package className="h-4 w-4" /></span><div className="min-w-40 flex-1"><p className="font-medium">{product.name}</p><p className="text-xs text-muted-foreground">{product.store} · {product.price}</p></div><p className="text-sm"><b>{product.clicks}</b> <span className="text-muted-foreground">clicks</span></p><p className="text-sm"><b>{product.orders}</b> <span className="text-muted-foreground">orders</span></p><Button size="sm" variant="outline">Share <ExternalLink className="h-3.5 w-3.5" /></Button></div>)}</CardContent></Card></div>; }

export function ProductsPage() { const [scope, setScope] = useScope(); return <div className="space-y-6"><PageHeader title="Products" description="Discover products from your connected brand stores and share what you love." actions={<StoreSelector scope={scope} setScope={setScope} />} /><Metrics scope={scope} /><Card className="shadow-card"><CardHeader className="p-5 pb-3"><CardTitle>{scope === "all" ? "Featured across your stores" : `${scopeName[scope]} products`}</CardTitle><p className="mt-1 text-sm text-muted-foreground">Your product recommendations and their live performance.</p></CardHeader><CardContent className="grid gap-4 p-5 pt-2 md:grid-cols-2 xl:grid-cols-3">{filterForScope(products, scope).map((product) => <div key={product.name} className="rounded-xl border p-4"><div className={`grid h-32 place-items-center rounded-lg ${product.tone}`}><Package className="h-8 w-8" /></div><p className="mt-4 font-semibold">{product.name}</p><p className="mt-1 text-sm text-muted-foreground">{product.store}</p><div className="mt-3 flex items-center justify-between"><span className="font-semibold">{product.price}</span><Badge variant="secondary">{product.orders} sold</Badge></div><Button className="mt-4 w-full" variant="outline">Get share link <Link2 className="h-4 w-4" /></Button></div>)}</CardContent></Card></div>; }

export function LinksPage() { const [scope, setScope] = useScope(); const data = scopeData[scope]; const links = filterForScope(products, scope); return <div className="space-y-6"><PageHeader title="Links" description="Create and manage trackable links for your storefront and content." actions={<StoreSelector scope={scope} setScope={setScope} />} /><Metrics scope={scope} /><Card className="shadow-card"><CardHeader className="flex-row items-center justify-between space-y-0 p-5 pb-3"><div><CardTitle>My tracked links</CardTitle><p className="mt-1 text-sm text-muted-foreground">{scope === "all" ? "All stores combined" : `Links for ${scopeName[scope]}`}</p></div><Button><Link2 className="h-4 w-4" /> Create link</Button></CardHeader><CardContent className="space-y-3 p-5 pt-1">{links.map((product) => <div key={product.name} className="flex flex-wrap items-center gap-3 rounded-xl border p-4"><span className={`grid h-10 w-10 place-items-center rounded-lg ${product.tone}`}><Link2 className="h-4 w-4" /></span><div className="min-w-52 flex-1"><p className="font-medium">{product.name}</p><p className="mt-1 truncate text-xs text-muted-foreground">mgi.to/meerastyles/{product.name.toLowerCase().replaceAll(" ", "-")}</p></div><div className="text-sm"><p className="font-semibold">{product.clicks}</p><p className="text-xs text-muted-foreground">clicks</p></div><div className="text-sm"><p className="font-semibold">{product.orders}</p><p className="text-xs text-muted-foreground">orders</p></div><Button variant="ghost" size="icon"><Copy className="h-4 w-4" /></Button></div>)}</CardContent></Card></div>; }

export function OrdersPage() { const [scope, setScope] = useScope(); return <div className="space-y-6"><PageHeader title="Orders" description="See every purchase attributed to your shared links and content." actions={<StoreSelector scope={scope} setScope={setScope} />} /><Metrics scope={scope} /><Card className="shadow-card"><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Order</th><th className="px-5 py-3 font-medium">Store</th><th className="px-5 py-3 font-medium">Order total</th><th className="px-5 py-3 font-medium">Your commission</th><th className="px-5 py-3 font-medium">Status</th></tr></thead><tbody>{filterForScope(orders, scope).map((order) => <tr key={order.id} className="border-b last:border-0"><td className="px-5 py-4"><p className="font-medium">{order.id}</p><p className="text-xs text-muted-foreground">{order.customer}</p></td><td className="px-5 py-4">{order.store}</td><td className="px-5 py-4 font-medium">{order.total}</td><td className="px-5 py-4 font-semibold text-primary">{order.commission}</td><td className="px-5 py-4"><Badge variant={order.status === "Approved" ? "outline" : "secondary"} className={order.status === "Approved" ? "border-success/20 bg-success/10 text-success" : ""}>{order.status}</Badge></td></tr>)}</tbody></table></CardContent></Card></div>; }

export function EarningsPage() { const [scope, setScope] = useScope(); const data = scopeData[scope]; return <div className="space-y-6"><PageHeader title="Earnings" description="Track commissions, payout status and the value you create for brands." actions={<StoreSelector scope={scope} setScope={setScope} />} /><section className="grid gap-4 sm:grid-cols-3"><Metric label="Available to withdraw" value={scope === "all" ? "₹18,400" : "₹8,200"} icon={BadgeIndianRupee} detail="Next payout Sep 20" /><Metric label="Pending approval" value={scope === "all" ? "₹6,280" : "₹2,600"} icon={TrendingUp} detail="From 12 orders" /><Metric label="Lifetime earnings" value={scope === "all" ? "₹1,46,820" : "₹64,180"} icon={Users} detail="Since joining" /></section><section className="grid gap-6 lg:grid-cols-3"><Card className="shadow-card lg:col-span-2"><CardHeader className="p-5 pb-3"><CardTitle>{scope === "all" ? "Combined earnings" : `${scopeName[scope]} earnings`}</CardTitle><p className="mt-1 text-sm text-muted-foreground">Monthly commissions across selected store scope.</p></CardHeader><CardContent className="p-5 pt-2"><div className="flex h-52 items-end gap-3">{[38, 51, 48, 66, 61, 79, 72, 94].map((height, index) => <div key={index} className="flex-1 rounded-t-lg bg-primary/20" style={{ height: `${height}%` }}><div className="h-full rounded-t-lg bg-primary" style={{ height: `${height - 18}%` }} /></div>)}</div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Feb</span><span>Apr</span><span>Jun</span><span>Aug</span><span>Sep</span></div></CardContent></Card><Card className="shadow-card"><CardContent className="p-6"><p className="text-sm text-muted-foreground">Current period</p><p className="mt-2 font-display text-3xl font-semibold">{data.earnings}</p><p className="mt-2 flex items-center gap-1 text-sm text-success"><ArrowUpRight className="h-4 w-4" />18.4% vs. last month</p><Button className="mt-6 w-full">Withdraw earnings</Button></CardContent></Card></section></div>; }
