import { ArrowUpRight, Bookmark, CheckCircle2, Clock3, MapPin, Search, Sparkles, Users } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/app/PageHeader";

const opportunities = [
  { brand: "Glow Theory", campaign: "Everyday Radiance", category: "Beauty & skincare", payment: "₹18,000 – ₹25,000", deliverables: "1 Reel + 3 Stories", applicants: 14, deadline: "Apply by Sep 22", match: 96, tone: "from-rose-500 via-orange-400 to-amber-300", logo: "GT", featured: true },
  { brand: "Urban Threads", campaign: "Winter Layers Edit", category: "Fashion", payment: "₹22,000 – ₹30,000", deliverables: "2 Reels + 1 Post", applicants: 21, deadline: "Apply by Sep 24", match: 92, tone: "from-violet-600 via-indigo-500 to-sky-400", logo: "UT", featured: true },
  { brand: "Kind Kitchen", campaign: "Mindful Mornings", category: "Food & wellness", payment: "₹12,000 – ₹16,000", deliverables: "1 Reel + 2 Stories", applicants: 8, deadline: "Apply by Sep 28", match: 88, tone: "from-emerald-500 via-teal-400 to-cyan-300", logo: "KK", featured: false },
  { brand: "Luma Home", campaign: "Spaces That Feel Like You", category: "Home & living", payment: "₹15,000 – ₹20,000", deliverables: "1 Reel + 1 Carousel", applicants: 17, deadline: "Apply by Oct 02", match: 83, tone: "from-fuchsia-500 via-pink-400 to-rose-300", logo: "LH", featured: false },
  { brand: "Move Better", campaign: "30 Day Reset", category: "Fitness", payment: "₹20,000 – ₹28,000", deliverables: "2 Reels + 4 Stories", applicants: 11, deadline: "Apply by Oct 04", match: 79, tone: "from-blue-600 via-cyan-400 to-teal-300", logo: "MB", featured: false },
  { brand: "Paper & Co.", campaign: "The Joy of Journaling", category: "Lifestyle", payment: "₹10,000 – ₹14,000", deliverables: "1 Reel + 1 Post", applicants: 6, deadline: "Apply by Oct 06", match: 76, tone: "from-amber-500 via-orange-400 to-yellow-300", logo: "PC", featured: false },
];

const categories = ["For you", "Fashion", "Beauty", "Food & wellness", "Lifestyle", "Fitness"];

export function DiscoverPage() {
  return <div className="space-y-6">
    <PageHeader title="Discover opportunities" description="Find brand partnerships that fit your audience and creative style." />
    <Card className="overflow-hidden border-primary/20 bg-gradient-to-r from-primary/10 via-primary/5 to-transparent shadow-card"><CardContent className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="h-5 w-5" /></span><div><p className="font-display text-lg font-semibold">Your profile is a strong match</p><p className="mt-1 text-sm text-muted-foreground">Complete your media kit to unlock more campaign invitations.</p></div></div><Button variant="outline">Complete profile <ArrowUpRight className="h-4 w-4" /></Button></CardContent></Card>
    <div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="bg-card pl-9" placeholder="Search brands, categories or campaigns" /></div><Button variant="outline">Remote & India</Button><Button variant="outline">All budgets</Button></div>
    <div className="flex gap-2 overflow-x-auto pb-1">{categories.map((category, index) => <Button key={category} variant={index === 0 ? "default" : "outline"} size="sm" className="shrink-0">{category}</Button>)}</div>
    <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{opportunities.map((opportunity) => <OpportunityCard key={opportunity.campaign} opportunity={opportunity} />)}</section>
    <Card className="shadow-card"><CardHeader className="p-5 pb-2"><CardTitle>How matches work</CardTitle><p className="mt-1 text-sm text-muted-foreground">We recommend campaigns based on your audience, content and category fit.</p></CardHeader><CardContent className="grid gap-4 p-5 pt-3 sm:grid-cols-3"><MatchStep icon={Users} title="Audience fit" text="Your follower demographics align with brand goals." /><MatchStep icon={Sparkles} title="Creative fit" text="Your content style matches their campaign brief." /><MatchStep icon={CheckCircle2} title="Profile readiness" text="Complete details help brands review you faster." /></CardContent></Card>
  </div>;
}

function OpportunityCard({ opportunity }: { opportunity: (typeof opportunities)[number] }) {
  return <Card className="group overflow-hidden shadow-card transition-shadow hover:shadow-lg"><div className={`relative h-28 bg-gradient-to-br ${opportunity.tone} p-4`}><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/90 text-sm font-bold text-foreground shadow-sm">{opportunity.logo}</span><div className="absolute right-3 top-3 flex gap-2">{opportunity.featured ? <Badge className="bg-white/20 text-white hover:bg-white/20">Featured</Badge> : null}<Button variant="secondary" size="icon" className="h-8 w-8 bg-white/85 hover:bg-white"><Bookmark className="h-4 w-4" /></Button></div></div><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">{opportunity.brand}</p><h2 className="mt-1 font-display text-lg font-semibold leading-tight">{opportunity.campaign}</h2></div><Badge className="shrink-0 bg-success/15 text-success hover:bg-success/15">{opportunity.match}% match</Badge></div><p className="mt-2 text-sm text-muted-foreground">{opportunity.category}</p><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-muted/55 p-3 text-sm"><div><p className="text-xs text-muted-foreground">Budget</p><p className="mt-1 font-semibold">{opportunity.payment}</p></div><div><p className="text-xs text-muted-foreground">Deliverables</p><p className="mt-1 font-semibold">{opportunity.deliverables}</p></div></div><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{opportunity.deadline}</span><span>{opportunity.applicants} applied</span></div><Button className="mt-4 w-full">View opportunity <ArrowUpRight className="h-4 w-4" /></Button></CardContent></Card>;
}
function MatchStep({ icon: Icon, title, text }: { icon: typeof Users; title: string; text: string }) { return <div className="flex gap-3 rounded-xl border p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="h-4 w-4" /></span><div><p className="font-medium">{title}</p><p className="mt-1 text-sm leading-5 text-muted-foreground">{text}</p></div></div>; }
