import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { PageHeader } from "@/components/app/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { apiClient } from "@/lib/api/client";
import { Route } from "@/routes/store-admin/orders/$orderId";
export function OrderDetailsPage(){const {orderId}=Route.useParams();const q=useQuery({queryKey:["store","orders",orderId],queryFn:async()=> (await apiClient.get<{order:any}>(`/store/orders/${orderId}`)).data.order});if(q.isLoading)return <div className="h-80 animate-pulse rounded-xl bg-muted"/>;const order=q.data;if(!order)return <Card><CardContent className="p-6 text-destructive">Unable to load order details.</CardContent></Card>;const raw=order.payload??{};const lines=raw.lineItems?.nodes??raw.lineItems??[];const address=raw.shippingAddress;return <div className="space-y-6"><Link to="/store-admin/orders" className="inline-flex items-center gap-2 text-sm text-primary"><ArrowLeft className="h-4 w-4"/> Orders</Link><PageHeader title={order.name} description={order.email??"Guest checkout"}/><section className="grid gap-6 lg:grid-cols-2"><Card><CardContent className="space-y-4 p-6"><div className="flex gap-2"><Badge>{order.financialStatus??"Pending"}</Badge><Badge variant="secondary">{order.fulfillmentStatus??"Unfulfilled"}</Badge></div><p className="text-2xl font-semibold">{order.currency??""} {order.total??"0"}</p><p className="text-sm text-muted-foreground">{order.processedAt?new Date(order.processedAt).toLocaleString():"Date unavailable"}</p></CardContent></Card><Card><CardContent className="p-6"><h2 className="font-semibold">Shipping address</h2><p className="mt-3 text-sm text-muted-foreground">{address?[address.address1,address.address2,address.city,address.province,address.zip,address.country].filter(Boolean).join(", "):"No shipping address"}</p></CardContent></Card></section><Card><CardContent className="p-6"><h2 className="font-semibold">Items ({lines.length})</h2><div className="mt-4 space-y-3">{lines.map((line:any,index:number)=><div key={line.id??index} className="flex justify-between border-b pb-3 text-sm"><span>{line.title}{line.variant?.title?` · ${line.variant.title}`:""}<span className="ml-2 text-muted-foreground">× {line.quantity}</span></span><span>{line.sku??""}</span></div>)}</div></CardContent></Card></div>}
