import { Prisma } from '@prisma/client';
import type { FastifyPluginAsync } from 'fastify';
import { requireRole } from '../../shared/auth/authorization.js';
import { AppError } from '../../shared/errors/app-error.js';
import { decryptToken } from '../instagram/instagram.crypto.js';
type Node = Record<string, any>; type Page = { items?: Node[]; pageInfo?: { hasNextPage: boolean; endCursor: string | null }; error?: string };
const query = `query Orders($after:String){orders(first:100,after:$after,sortKey:PROCESSED_AT,reverse:true){nodes{id name email tags customAttributes{key value} displayFinancialStatus displayFulfillmentStatus processedAt totalPriceSet{shopMoney{amount currencyCode}} lineItems(first:250){nodes{title quantity sku variant{title}}} shippingAddress{address1 address2 city province zip country} customer{firstName lastName email} } pageInfo{hasNextPage endCursor}}}`;
export const storeOrdersRoutes: FastifyPluginAsync = async (app) => {
  const prisma = app.prisma as any;
  async function store(userId: string) { const s = await prisma.organization.findFirst({ where: { ownerId: userId }, select: { id: true, platform: true, connectionStatus: true, shopDomain: true, appUrl: true, shopifyConnectionMethod: true, encryptedShopifyAccessToken: true } }); if (!s || s.platform !== 'SHOPIFY' || s.connectionStatus !== 'CONNECTED' || !s.shopDomain || !s.encryptedShopifyAccessToken || (s.shopifyConnectionMethod === 'CLI_APP' && !s.appUrl)) throw new AppError('SHOPIFY_NOT_CONNECTED', 'Complete the Shopify connection before syncing orders.', 409); return s; }
  async function page(s: Awaited<ReturnType<typeof store>>, after: string | null) { const shop = s.shopDomain!.replace(/^https?:\/\//, '').replace(/\/$/, ''); const token = decryptToken(s.encryptedShopifyAccessToken!); try { if (s.shopifyConnectionMethod === 'CLI_APP') { const u = new URL(`${s.appUrl!.replace(/\/$/, '')}/app/api/bridge/orders`); u.searchParams.set('shop', shop); u.searchParams.set('first', '100'); if (after) u.searchParams.set('after', after); const r = await fetch(u, { headers: { 'X-MegaChat-Bridge-Token': token } }); const b = await r.json().catch(() => null) as Page | null; if (!r.ok || !b?.items || !b.pageInfo) throw new AppError('SHOPIFY_ORDERS_UNAVAILABLE', b?.error ?? 'Shopify bridge could not return orders.', 502); return b as Required<Page>; } const r = await fetch(`https://${shop}/admin/api/2025-01/graphql.json`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Shopify-Access-Token': token }, body: JSON.stringify({ query, variables: { after } }) }); const b = await r.json().catch(() => null) as any; const o = b?.data?.orders; if (!r.ok || b?.errors?.length || !o?.nodes) throw new AppError('SHOPIFY_ORDERS_UNAVAILABLE', b?.errors?.[0]?.message ?? 'Shopify could not return orders.', 502); return { items: o.nodes, pageInfo: o.pageInfo }; } catch (e) { if (e instanceof AppError) throw e; throw new AppError('SHOPIFY_UNAVAILABLE', 'Unable to reach the connected Shopify store.', 502); } }
  app.get('/store/orders', async req => { const a = requireRole(req, ['STORE_OWNER']); const s = await store(a.userId); const q = req.query as { page?: string; limit?: string }; const page = Math.max(1, Number(q.page) || 1), limit = Math.min(100, Math.max(1, Number(q.limit) || 25)), where = { organizationId: s.id }; const [rows, total] = await Promise.all([prisma.shopifyOrder.findMany({ where, orderBy: { processedAt: 'desc' }, skip: (page - 1) * limit, take: limit }), prisma.shopifyOrder.count({ where })]); return { orders: rows, pagination: { page, limit, total, totalPages: Math.max(1, Math.ceil(total / limit)) } }; });
  app.post('/store/orders/sync', async req => { const a = requireRole(req, ['STORE_OWNER']); const s = await store(a.userId); let after: string | null = null, synced = 0; do { const p = await page(s, after); await Promise.all(p.items.map(async (item: Node) => { const raw = item.raw ?? item, total = raw.totalPriceSet?.shopMoney; const d = { shopifyId: item.shopifyGid ?? raw.id, name: item.name ?? raw.name, email: item.customerEmail ?? raw.email ?? raw.customer?.email ?? null, currency: item.currencyCode ?? total?.currencyCode ?? null, total: item.totalAmount ?? total?.amount ?? null, financialStatus: item.financialStatus ?? raw.displayFinancialStatus ?? null, fulfillmentStatus: raw.displayFulfillmentStatus ?? null, processedAt: (item.shopifyCreatedAt ?? raw.processedAt) ? new Date(item.shopifyCreatedAt ?? raw.processedAt) : null, payload: raw as Prisma.InputJsonValue }; const order = await prisma.shopifyOrder.upsert({ where: { organizationId_shopifyId: { organizationId: s.id, shopifyId: d.shopifyId } }, create: { organizationId: s.id, ...d }, update: d }); const attributes = raw.customAttributes ?? item.customAttributes ?? []; const linkSlug = attributes.find((attribute: Node) => (attribute.key ?? attribute.name) === 'mi_link')?.value; const tags = raw.tags ?? item.tags ?? []; if (!linkSlug || tags.includes('InfluencerSample')) return; const link = await prisma.affiliateLink.findFirst({ where: { organizationId: s.id, slug: String(linkSlug) }, select: { id: true, creatorId: true, commissionRate: true } }); if (!link) return; const amount = Number(d.total ?? 0); const status = d.financialStatus === 'REFUNDED' || d.financialStatus === 'refunded' ? 'REVERSED' : 'PENDING'; await prisma.affiliateCommission.upsert({ where: { shopifyOrderId: order.id }, create: { organizationId: s.id, linkId: link.id, creatorId: link.creatorId, shopifyOrderId: order.id, orderAmount: amount, commissionRate: link.commissionRate, amount: amount * Number(link.commissionRate) / 100, status }, update: { status } }); })); synced += p.items.length; after = p.pageInfo.hasNextPage ? p.pageInfo.endCursor : null; } while (after); return { synced }; });
  app.get('/store/orders/:orderId', async req => { const a = requireRole(req, ['STORE_OWNER']); const s = await store(a.userId); const { orderId } = req.params as { orderId: string }; const order = await prisma.shopifyOrder.findFirst({ where: { id: orderId, organizationId: s.id } }); if (!order) throw new AppError('ORDER_NOT_FOUND', 'Order not found.', 404); return { order }; });
};
