import argon2 from 'argon2';
import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';

import { requireRole } from '../../shared/auth/authorization.js';
import { AppError } from '../../shared/errors/app-error.js';
import { parseOrThrow } from '../../shared/validation/pagination.js';
import { encryptToken } from '../instagram/instagram.crypto.js';

const optionalText = z.string().trim().max(255).optional().transform((value) => value || null);
const storeSchema = z.object({ name: z.string().trim().min(2).max(120), ownerEmail: z.string().email(), ownerName: z.string().trim().min(2).max(120), password: z.string().trim().min(12).max(200).optional().or(z.literal('')).transform((value) => value || undefined), platform: z.enum(['SHOPIFY', 'WOOCOMMERCE', 'CUSTOM']), connectionStatus: z.enum(['PENDING', 'CONNECTED', 'DISABLED']), category: optionalText, logoUrl: z.string().url().optional().or(z.literal('')).transform((value) => value || null), shopDomain: optionalText, appUrl: z.string().url().optional().or(z.literal('')).transform((value) => value || null), apiUrl: z.string().url().optional().or(z.literal('')).transform((value) => value || null), shopifyConnectionMethod: z.enum(['CLI_APP', 'ADMIN_API']).optional().nullable(), shopifyAccessToken: z.string().trim().min(1).max(500).optional().or(z.literal('')).transform((value) => value || undefined) });
const idSchema = z.object({ storeId: z.string().cuid() });

const storeSelect = { id: true, name: true, slug: true, platform: true, connectionStatus: true, category: true, logoUrl: true, shopDomain: true, appUrl: true, apiUrl: true, shopifyConnectionMethod: true, encryptedShopifyAccessToken: true, createdAt: true, owner: { select: { id: true, displayName: true, email: true } }, _count: { select: { assignments: true } } } as const;
function publicStore(store: { encryptedShopifyAccessToken: string | null; [key: string]: unknown }) { const { encryptedShopifyAccessToken, ...value } = store; return { ...value, hasShopifyAccessToken: Boolean(encryptedShopifyAccessToken) }; }
function slugify(value: string) { return `${value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${Math.random().toString(36).slice(2, 7)}`; }

export const adminStoreRoutes: FastifyPluginAsync = async (app) => {
  app.get('/admin/stores', async (request) => { requireRole(request, ['ADMIN']); const stores = await app.prisma.organization.findMany({ orderBy: { createdAt: 'desc' }, select: storeSelect }); return { stores: stores.map(publicStore) }; });
  app.post('/admin/stores', async (request, reply) => { requireRole(request, ['ADMIN']); const input = parseOrThrow(storeSchema.extend({ password: z.string().min(12).max(200) }), request.body); const owner = await app.prisma.user.findUnique({ where: { email: input.ownerEmail } }); if (owner && owner.role !== 'STORE_OWNER') throw new AppError('EMAIL_IN_USE', 'This email belongs to a different account type.', 409); const store = await app.prisma.$transaction(async (tx) => { const storeOwner = owner ?? await tx.user.create({ data: { email: input.ownerEmail, displayName: input.ownerName, passwordHash: await argon2.hash(input.password), role: 'STORE_OWNER' } }); return tx.organization.create({ data: { name: input.name, slug: slugify(input.name), ownerId: storeOwner.id, platform: input.platform, connectionStatus: input.connectionStatus, category: input.category, logoUrl: input.logoUrl, shopDomain: input.shopDomain, appUrl: input.appUrl, apiUrl: input.apiUrl, shopifyConnectionMethod: input.platform === 'SHOPIFY' ? input.shopifyConnectionMethod : null, encryptedShopifyAccessToken: input.shopifyAccessToken ? encryptToken(input.shopifyAccessToken) : null }, select: storeSelect }); }); return reply.status(201).send({ store: publicStore(store) }); });
  app.patch('/admin/stores/:storeId', async (request) => { requireRole(request, ['ADMIN']); const { storeId } = parseOrThrow(idSchema, request.params); const input = parseOrThrow(storeSchema, request.body); const existing = await app.prisma.organization.findUnique({ where: { id: storeId }, select: { ownerId: true } }); if (!existing) throw new AppError('STORE_NOT_FOUND', 'Store not found.', 404); const store = await app.prisma.$transaction(async (tx) => { await tx.user.update({ where: { id: existing.ownerId }, data: { email: input.ownerEmail, displayName: input.ownerName, ...(input.password ? { passwordHash: await argon2.hash(input.password) } : {}) } }); return tx.organization.update({ where: { id: storeId }, data: { name: input.name, platform: input.platform, connectionStatus: input.connectionStatus, category: input.category, logoUrl: input.logoUrl, shopDomain: input.shopDomain, appUrl: input.appUrl, apiUrl: input.apiUrl, shopifyConnectionMethod: input.platform === 'SHOPIFY' ? input.shopifyConnectionMethod : null, ...(input.shopifyAccessToken ? { encryptedShopifyAccessToken: encryptToken(input.shopifyAccessToken) } : {}) }, select: storeSelect }); }); return { store: publicStore(store) }; });
  app.get('/admin/stores/:storeId/assignments', async (request) => { requireRole(request, ['ADMIN']); const { storeId } = parseOrThrow(idSchema, request.params); const store = await app.prisma.organization.findUnique({ where: { id: storeId }, select: { id: true, name: true } }); if (!store) throw new AppError('STORE_NOT_FOUND', 'Store not found.', 404); const influencers = await app.prisma.user.findMany({ where: { role: 'INFLUENCER', status: 'ACTIVE' }, select: { id: true, displayName: true, instagramConnection: { select: { username: true } }, storeAssignments: { where: { organizationId: storeId }, select: { id: true } } } }); return { store, influencers: influencers.map(({ instagramConnection, storeAssignments, ...influencer }) => ({ ...influencer, instagramUsername: instagramConnection?.username ?? null, assigned: storeAssignments.length > 0 })) }; });
  app.put('/admin/stores/:storeId/assignments', async (request) => { requireRole(request, ['ADMIN']); const { storeId } = parseOrThrow(idSchema, request.params); const { influencerIds } = parseOrThrow(z.object({ influencerIds: z.array(z.string().cuid()).max(500) }), request.body); const uniqueIds = [...new Set(influencerIds)]; const count = await app.prisma.user.count({ where: { id: { in: uniqueIds }, role: 'INFLUENCER', status: 'ACTIVE' } }); if (count !== uniqueIds.length) throw new AppError('INVALID_ASSIGNMENT', 'Assignments must be active influencer accounts.', 400); await app.prisma.$transaction([app.prisma.storeInfluencerAssignment.deleteMany({ where: { organizationId: storeId } }), app.prisma.storeInfluencerAssignment.createMany({ data: uniqueIds.map((influencerId) => ({ organizationId: storeId, influencerId })) })]); return { ok: true }; });
};
