/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InfluencerRouteImport } from './routes/influencer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StoreAdminRouteImport } from './routes/store-admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPageRouteImport } from './routes/admin/$page'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAttributionRouteImport } from './routes/admin/attribution'
import { Route as AdminBrandsRouteImport } from './routes/admin/brands'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminCommissionsRouteImport } from './routes/admin/commissions'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminInfluencersRouteImport } from './routes/admin/influencers'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSocialRouteImport } from './routes/admin/social'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as InfluencerIndexRouteImport } from './routes/influencer.index'
import { Route as InfluencerPageRouteImport } from './routes/influencer/$page'
import { Route as InfluencerAnalyticsRouteImport } from './routes/influencer/analytics'
import { Route as InfluencerCampaignsRouteImport } from './routes/influencer/campaigns'
import { Route as InfluencerDashboardRouteImport } from './routes/influencer/dashboard'
import { Route as InfluencerDiscoverRouteImport } from './routes/influencer/discover'
import { Route as InfluencerEarningsRouteImport } from './routes/influencer/earnings'
import { Route as InfluencerInstagramAutomationRouteImport } from './routes/influencer/instagram-automation'
import { Route as InfluencerLinksRouteImport } from './routes/influencer/links'
import { Route as InfluencerNotificationsRouteImport } from './routes/influencer/notifications'
import { Route as InfluencerOrdersRouteImport } from './routes/influencer/orders'
import { Route as InfluencerProductsRouteImport } from './routes/influencer/products'
import { Route as InfluencerProfileRouteImport } from './routes/influencer/profile'
import { Route as InfluencerStoreRouteImport } from './routes/influencer/store'
import { Route as InfluencerSupportRouteImport } from './routes/influencer/support'
import { Route as StoreAdminIndexRouteImport } from './routes/store-admin.index'
import { Route as StoreAdminPageRouteImport } from './routes/store-admin/$page'
import { Route as StoreAdminAffiliateRouteImport } from './routes/store-admin/affiliate'
import { Route as StoreAdminAnalyticsRouteImport } from './routes/store-admin/analytics'
import { Route as StoreAdminCampaignsRouteImport } from './routes/store-admin/campaigns'
import { Route as StoreAdminCommissionsRouteImport } from './routes/store-admin/commissions'
import { Route as StoreAdminCreatorsRouteImport } from './routes/store-admin/creators'
import { Route as StoreAdminCustomersRouteImport } from './routes/store-admin/customers'
import { Route as StoreAdminDashboardRouteImport } from './routes/store-admin/dashboard'
import { Route as StoreAdminDiscountsRouteImport } from './routes/store-admin/discounts'
import { Route as StoreAdminIntegrationsRouteImport } from './routes/store-admin/integrations'
import { Route as StoreAdminOrdersRouteImport } from './routes/store-admin/orders'
import { Route as StoreAdminProductsRouteImport } from './routes/store-admin/products'
import { Route as StoreAdminReportsRouteImport } from './routes/store-admin/reports'
import { Route as StoreAdminSettingsRouteImport } from './routes/store-admin/settings'
import { Route as StoreAdminStoreRouteImport } from './routes/store-admin/store'
import { Route as StoreLoginRouteImport } from './routes/store/login'
import { Route as AdminInfluencersIndexRouteImport } from './routes/admin/influencers.index'
import { Route as AdminInfluencersInfluencerIdRouteImport } from './routes/admin/influencers/$influencerId'
import { Route as InfluencerCampaignsIndexRouteImport } from './routes/influencer/campaigns/index'
import { Route as InfluencerCampaignsCampaignIdRouteImport } from './routes/influencer/campaigns/$campaignId'
import { Route as InfluencerInstagramAutomationIndexRouteImport } from './routes/influencer/instagram-automation/index'
import { Route as StoreAdminCreatorsIndexRouteImport } from './routes/store-admin/creators/index'
import { Route as StoreAdminCreatorsCreatorIdRouteImport } from './routes/store-admin/creators/$creatorId'
import { Route as StoreAdminOrdersIndexRouteImport } from './routes/store-admin/orders/index'
import { Route as StoreAdminOrdersOrderIdRouteImport } from './routes/store-admin/orders/$orderId'
import { Route as StoreAdminProductsIndexRouteImport } from './routes/store-admin/products/index'
import { Route as StoreAdminProductsProductIdRouteImport } from './routes/store-admin/products/$productId'
import { Route as InfluencerInstagramAutomationRulesRuleIdRouteImport } from './routes/influencer/instagram-automation/rules/$ruleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerRoute = InfluencerRouteImport.update({
  id: '/influencer',
  path: '/influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreAdminRoute = StoreAdminRouteImport.update({
  id: '/store-admin',
  path: '/store-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttributionRoute = AdminAttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfluencersRoute = AdminInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const InfluencerIndexRoute = InfluencerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerPageRoute = InfluencerPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerAnalyticsRoute = InfluencerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerCampaignsRoute = InfluencerCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerDashboardRoute = InfluencerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerDiscoverRoute = InfluencerDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerEarningsRoute = InfluencerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerInstagramAutomationRoute =
  InfluencerInstagramAutomationRouteImport.update({
    id: '/instagram-automation',
    path: '/instagram-automation',
    getParentRoute: () => InfluencerRoute,
  } as any)
const InfluencerLinksRoute = InfluencerLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerNotificationsRoute = InfluencerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerOrdersRoute = InfluencerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerProductsRoute = InfluencerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerProfileRoute = InfluencerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerStoreRoute = InfluencerStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => InfluencerRoute,
} as any)
const InfluencerSupportRoute = InfluencerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => InfluencerRoute,
} as any)
const StoreAdminIndexRoute = StoreAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminPageRoute = StoreAdminPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminAffiliateRoute = StoreAdminAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminAnalyticsRoute = StoreAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminCampaignsRoute = StoreAdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminCommissionsRoute = StoreAdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminCreatorsRoute = StoreAdminCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminCustomersRoute = StoreAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminDashboardRoute = StoreAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminDiscountsRoute = StoreAdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminIntegrationsRoute = StoreAdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminOrdersRoute = StoreAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminProductsRoute = StoreAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminReportsRoute = StoreAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminSettingsRoute = StoreAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreAdminStoreRoute = StoreAdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => StoreAdminRoute,
} as any)
const StoreLoginRoute = StoreLoginRouteImport.update({
  id: '/store/login',
  path: '/store/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInfluencersIndexRoute = AdminInfluencersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInfluencersRoute,
} as any)
const AdminInfluencersInfluencerIdRoute =
  AdminInfluencersInfluencerIdRouteImport.update({
    id: '/$influencerId',
    path: '/$influencerId',
    getParentRoute: () => AdminInfluencersRoute,
  } as any)
const InfluencerCampaignsIndexRoute =
  InfluencerCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InfluencerCampaignsRoute,
  } as any)
const InfluencerCampaignsCampaignIdRoute =
  InfluencerCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => InfluencerCampaignsRoute,
  } as any)
const InfluencerInstagramAutomationIndexRoute =
  InfluencerInstagramAutomationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => InfluencerInstagramAutomationRoute,
  } as any)
const StoreAdminCreatorsIndexRoute = StoreAdminCreatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreAdminCreatorsRoute,
} as any)
const StoreAdminCreatorsCreatorIdRoute =
  StoreAdminCreatorsCreatorIdRouteImport.update({
    id: '/$creatorId',
    path: '/$creatorId',
    getParentRoute: () => StoreAdminCreatorsRoute,
  } as any)
const StoreAdminOrdersIndexRoute = StoreAdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreAdminOrdersRoute,
} as any)
const StoreAdminOrdersOrderIdRoute = StoreAdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => StoreAdminOrdersRoute,
} as any)
const StoreAdminProductsIndexRoute = StoreAdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreAdminProductsRoute,
} as any)
const StoreAdminProductsProductIdRoute =
  StoreAdminProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => StoreAdminProductsRoute,
  } as any)
const InfluencerInstagramAutomationRulesRuleIdRoute =
  InfluencerInstagramAutomationRulesRuleIdRouteImport.update({
    id: '/rules/$ruleId',
    path: '/rules/$ruleId',
    getParentRoute: () => InfluencerInstagramAutomationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/influencer': typeof InfluencerRouteWithChildren
  '/login': typeof LoginRoute
  '/store-admin': typeof StoreAdminRouteWithChildren
  '/admin/$page': typeof AdminPageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attribution': typeof AdminAttributionRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/influencers': typeof AdminInfluencersRouteWithChildren
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/influencer/$page': typeof InfluencerPageRoute
  '/influencer/analytics': typeof InfluencerAnalyticsRoute
  '/influencer/campaigns': typeof InfluencerCampaignsRouteWithChildren
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/influencer/discover': typeof InfluencerDiscoverRoute
  '/influencer/earnings': typeof InfluencerEarningsRoute
  '/influencer/instagram-automation': typeof InfluencerInstagramAutomationRouteWithChildren
  '/influencer/links': typeof InfluencerLinksRoute
  '/influencer/notifications': typeof InfluencerNotificationsRoute
  '/influencer/orders': typeof InfluencerOrdersRoute
  '/influencer/products': typeof InfluencerProductsRoute
  '/influencer/profile': typeof InfluencerProfileRoute
  '/influencer/store': typeof InfluencerStoreRoute
  '/influencer/support': typeof InfluencerSupportRoute
  '/store-admin/$page': typeof StoreAdminPageRoute
  '/store-admin/affiliate': typeof StoreAdminAffiliateRoute
  '/store-admin/analytics': typeof StoreAdminAnalyticsRoute
  '/store-admin/campaigns': typeof StoreAdminCampaignsRoute
  '/store-admin/commissions': typeof StoreAdminCommissionsRoute
  '/store-admin/creators': typeof StoreAdminCreatorsRouteWithChildren
  '/store-admin/customers': typeof StoreAdminCustomersRoute
  '/store-admin/dashboard': typeof StoreAdminDashboardRoute
  '/store-admin/discounts': typeof StoreAdminDiscountsRoute
  '/store-admin/integrations': typeof StoreAdminIntegrationsRoute
  '/store-admin/orders': typeof StoreAdminOrdersRouteWithChildren
  '/store-admin/products': typeof StoreAdminProductsRouteWithChildren
  '/store-admin/reports': typeof StoreAdminReportsRoute
  '/store-admin/settings': typeof StoreAdminSettingsRoute
  '/store-admin/store': typeof StoreAdminStoreRoute
  '/store/login': typeof StoreLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/store-admin/': typeof StoreAdminIndexRoute
  '/admin/influencers/$influencerId': typeof AdminInfluencersInfluencerIdRoute
  '/influencer/campaigns/$campaignId': typeof InfluencerCampaignsCampaignIdRoute
  '/store-admin/creators/$creatorId': typeof StoreAdminCreatorsCreatorIdRoute
  '/store-admin/orders/$orderId': typeof StoreAdminOrdersOrderIdRoute
  '/store-admin/products/$productId': typeof StoreAdminProductsProductIdRoute
  '/admin/influencers/': typeof AdminInfluencersIndexRoute
  '/influencer/campaigns/': typeof InfluencerCampaignsIndexRoute
  '/influencer/instagram-automation/': typeof InfluencerInstagramAutomationIndexRoute
  '/store-admin/creators/': typeof StoreAdminCreatorsIndexRoute
  '/store-admin/orders/': typeof StoreAdminOrdersIndexRoute
  '/store-admin/products/': typeof StoreAdminProductsIndexRoute
  '/influencer/instagram-automation/rules/$ruleId': typeof InfluencerInstagramAutomationRulesRuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attribution': typeof AdminAttributionRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/influencer/$page': typeof InfluencerPageRoute
  '/influencer/analytics': typeof InfluencerAnalyticsRoute
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/influencer/discover': typeof InfluencerDiscoverRoute
  '/influencer/earnings': typeof InfluencerEarningsRoute
  '/influencer/links': typeof InfluencerLinksRoute
  '/influencer/notifications': typeof InfluencerNotificationsRoute
  '/influencer/orders': typeof InfluencerOrdersRoute
  '/influencer/products': typeof InfluencerProductsRoute
  '/influencer/profile': typeof InfluencerProfileRoute
  '/influencer/store': typeof InfluencerStoreRoute
  '/influencer/support': typeof InfluencerSupportRoute
  '/store-admin/$page': typeof StoreAdminPageRoute
  '/store-admin/affiliate': typeof StoreAdminAffiliateRoute
  '/store-admin/analytics': typeof StoreAdminAnalyticsRoute
  '/store-admin/campaigns': typeof StoreAdminCampaignsRoute
  '/store-admin/commissions': typeof StoreAdminCommissionsRoute
  '/store-admin/customers': typeof StoreAdminCustomersRoute
  '/store-admin/dashboard': typeof StoreAdminDashboardRoute
  '/store-admin/discounts': typeof StoreAdminDiscountsRoute
  '/store-admin/integrations': typeof StoreAdminIntegrationsRoute
  '/store-admin/reports': typeof StoreAdminReportsRoute
  '/store-admin/settings': typeof StoreAdminSettingsRoute
  '/store-admin/store': typeof StoreAdminStoreRoute
  '/store/login': typeof StoreLoginRoute
  '/admin': typeof AdminIndexRoute
  '/influencer': typeof InfluencerIndexRoute
  '/store-admin': typeof StoreAdminIndexRoute
  '/admin/influencers/$influencerId': typeof AdminInfluencersInfluencerIdRoute
  '/influencer/campaigns/$campaignId': typeof InfluencerCampaignsCampaignIdRoute
  '/store-admin/creators/$creatorId': typeof StoreAdminCreatorsCreatorIdRoute
  '/store-admin/orders/$orderId': typeof StoreAdminOrdersOrderIdRoute
  '/store-admin/products/$productId': typeof StoreAdminProductsProductIdRoute
  '/admin/influencers': typeof AdminInfluencersIndexRoute
  '/influencer/campaigns': typeof InfluencerCampaignsIndexRoute
  '/influencer/instagram-automation': typeof InfluencerInstagramAutomationIndexRoute
  '/store-admin/creators': typeof StoreAdminCreatorsIndexRoute
  '/store-admin/orders': typeof StoreAdminOrdersIndexRoute
  '/store-admin/products': typeof StoreAdminProductsIndexRoute
  '/influencer/instagram-automation/rules/$ruleId': typeof InfluencerInstagramAutomationRulesRuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/influencer': typeof InfluencerRouteWithChildren
  '/login': typeof LoginRoute
  '/store-admin': typeof StoreAdminRouteWithChildren
  '/admin/$page': typeof AdminPageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/attribution': typeof AdminAttributionRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/influencers': typeof AdminInfluencersRouteWithChildren
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/influencer/$page': typeof InfluencerPageRoute
  '/influencer/analytics': typeof InfluencerAnalyticsRoute
  '/influencer/campaigns': typeof InfluencerCampaignsRouteWithChildren
  '/influencer/dashboard': typeof InfluencerDashboardRoute
  '/influencer/discover': typeof InfluencerDiscoverRoute
  '/influencer/earnings': typeof InfluencerEarningsRoute
  '/influencer/instagram-automation': typeof InfluencerInstagramAutomationRouteWithChildren
  '/influencer/links': typeof InfluencerLinksRoute
  '/influencer/notifications': typeof InfluencerNotificationsRoute
  '/influencer/orders': typeof InfluencerOrdersRoute
  '/influencer/products': typeof InfluencerProductsRoute
  '/influencer/profile': typeof InfluencerProfileRoute
  '/influencer/store': typeof InfluencerStoreRoute
  '/influencer/support': typeof InfluencerSupportRoute
  '/store-admin/$page': typeof StoreAdminPageRoute
  '/store-admin/affiliate': typeof StoreAdminAffiliateRoute
  '/store-admin/analytics': typeof StoreAdminAnalyticsRoute
  '/store-admin/campaigns': typeof StoreAdminCampaignsRoute
  '/store-admin/commissions': typeof StoreAdminCommissionsRoute
  '/store-admin/creators': typeof StoreAdminCreatorsRouteWithChildren
  '/store-admin/customers': typeof StoreAdminCustomersRoute
  '/store-admin/dashboard': typeof StoreAdminDashboardRoute
  '/store-admin/discounts': typeof StoreAdminDiscountsRoute
  '/store-admin/integrations': typeof StoreAdminIntegrationsRoute
  '/store-admin/orders': typeof StoreAdminOrdersRouteWithChildren
  '/store-admin/products': typeof StoreAdminProductsRouteWithChildren
  '/store-admin/reports': typeof StoreAdminReportsRoute
  '/store-admin/settings': typeof StoreAdminSettingsRoute
  '/store-admin/store': typeof StoreAdminStoreRoute
  '/store/login': typeof StoreLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/store-admin/': typeof StoreAdminIndexRoute
  '/admin/influencers/$influencerId': typeof AdminInfluencersInfluencerIdRoute
  '/influencer/campaigns/$campaignId': typeof InfluencerCampaignsCampaignIdRoute
  '/store-admin/creators/$creatorId': typeof StoreAdminCreatorsCreatorIdRoute
  '/store-admin/orders/$orderId': typeof StoreAdminOrdersOrderIdRoute
  '/store-admin/products/$productId': typeof StoreAdminProductsProductIdRoute
  '/admin/influencers/': typeof AdminInfluencersIndexRoute
  '/influencer/campaigns/': typeof InfluencerCampaignsIndexRoute
  '/influencer/instagram-automation/': typeof InfluencerInstagramAutomationIndexRoute
  '/store-admin/creators/': typeof StoreAdminCreatorsIndexRoute
  '/store-admin/orders/': typeof StoreAdminOrdersIndexRoute
  '/store-admin/products/': typeof StoreAdminProductsIndexRoute
  '/influencer/instagram-automation/rules/$ruleId': typeof InfluencerInstagramAutomationRulesRuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/influencer'
    | '/login'
    | '/store-admin'
    | '/admin/$page'
    | '/admin/analytics'
    | '/admin/attribution'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/influencers'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/stores'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/influencer/$page'
    | '/influencer/analytics'
    | '/influencer/campaigns'
    | '/influencer/dashboard'
    | '/influencer/discover'
    | '/influencer/earnings'
    | '/influencer/instagram-automation'
    | '/influencer/links'
    | '/influencer/notifications'
    | '/influencer/orders'
    | '/influencer/products'
    | '/influencer/profile'
    | '/influencer/store'
    | '/influencer/support'
    | '/store-admin/$page'
    | '/store-admin/affiliate'
    | '/store-admin/analytics'
    | '/store-admin/campaigns'
    | '/store-admin/commissions'
    | '/store-admin/creators'
    | '/store-admin/customers'
    | '/store-admin/dashboard'
    | '/store-admin/discounts'
    | '/store-admin/integrations'
    | '/store-admin/orders'
    | '/store-admin/products'
    | '/store-admin/reports'
    | '/store-admin/settings'
    | '/store-admin/store'
    | '/store/login'
    | '/admin/'
    | '/influencer/'
    | '/store-admin/'
    | '/admin/influencers/$influencerId'
    | '/influencer/campaigns/$campaignId'
    | '/store-admin/creators/$creatorId'
    | '/store-admin/orders/$orderId'
    | '/store-admin/products/$productId'
    | '/admin/influencers/'
    | '/influencer/campaigns/'
    | '/influencer/instagram-automation/'
    | '/store-admin/creators/'
    | '/store-admin/orders/'
    | '/store-admin/products/'
    | '/influencer/instagram-automation/rules/$ruleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/$page'
    | '/admin/analytics'
    | '/admin/attribution'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/stores'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/influencer/$page'
    | '/influencer/analytics'
    | '/influencer/dashboard'
    | '/influencer/discover'
    | '/influencer/earnings'
    | '/influencer/links'
    | '/influencer/notifications'
    | '/influencer/orders'
    | '/influencer/products'
    | '/influencer/profile'
    | '/influencer/store'
    | '/influencer/support'
    | '/store-admin/$page'
    | '/store-admin/affiliate'
    | '/store-admin/analytics'
    | '/store-admin/campaigns'
    | '/store-admin/commissions'
    | '/store-admin/customers'
    | '/store-admin/dashboard'
    | '/store-admin/discounts'
    | '/store-admin/integrations'
    | '/store-admin/reports'
    | '/store-admin/settings'
    | '/store-admin/store'
    | '/store/login'
    | '/admin'
    | '/influencer'
    | '/store-admin'
    | '/admin/influencers/$influencerId'
    | '/influencer/campaigns/$campaignId'
    | '/store-admin/creators/$creatorId'
    | '/store-admin/orders/$orderId'
    | '/store-admin/products/$productId'
    | '/admin/influencers'
    | '/influencer/campaigns'
    | '/influencer/instagram-automation'
    | '/store-admin/creators'
    | '/store-admin/orders'
    | '/store-admin/products'
    | '/influencer/instagram-automation/rules/$ruleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/influencer'
    | '/login'
    | '/store-admin'
    | '/admin/$page'
    | '/admin/analytics'
    | '/admin/attribution'
    | '/admin/brands'
    | '/admin/campaigns'
    | '/admin/commissions'
    | '/admin/dashboard'
    | '/admin/finance'
    | '/admin/influencers'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/stores'
    | '/admin/support'
    | '/admin/system'
    | '/admin/users'
    | '/influencer/$page'
    | '/influencer/analytics'
    | '/influencer/campaigns'
    | '/influencer/dashboard'
    | '/influencer/discover'
    | '/influencer/earnings'
    | '/influencer/instagram-automation'
    | '/influencer/links'
    | '/influencer/notifications'
    | '/influencer/orders'
    | '/influencer/products'
    | '/influencer/profile'
    | '/influencer/store'
    | '/influencer/support'
    | '/store-admin/$page'
    | '/store-admin/affiliate'
    | '/store-admin/analytics'
    | '/store-admin/campaigns'
    | '/store-admin/commissions'
    | '/store-admin/creators'
    | '/store-admin/customers'
    | '/store-admin/dashboard'
    | '/store-admin/discounts'
    | '/store-admin/integrations'
    | '/store-admin/orders'
    | '/store-admin/products'
    | '/store-admin/reports'
    | '/store-admin/settings'
    | '/store-admin/store'
    | '/store/login'
    | '/admin/'
    | '/influencer/'
    | '/store-admin/'
    | '/admin/influencers/$influencerId'
    | '/influencer/campaigns/$campaignId'
    | '/store-admin/creators/$creatorId'
    | '/store-admin/orders/$orderId'
    | '/store-admin/products/$productId'
    | '/admin/influencers/'
    | '/influencer/campaigns/'
    | '/influencer/instagram-automation/'
    | '/store-admin/creators/'
    | '/store-admin/orders/'
    | '/store-admin/products/'
    | '/influencer/instagram-automation/rules/$ruleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InfluencerRoute: typeof InfluencerRouteWithChildren
  LoginRoute: typeof LoginRoute
  StoreAdminRoute: typeof StoreAdminRouteWithChildren
  StoreLoginRoute: typeof StoreLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer': {
      id: '/influencer'
      path: '/influencer'
      fullPath: '/influencer'
      preLoaderRoute: typeof InfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-admin': {
      id: '/store-admin'
      path: '/store-admin'
      fullPath: '/store-admin'
      preLoaderRoute: typeof StoreAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$page': {
      id: '/admin/$page'
      path: '/$page'
      fullPath: '/admin/$page'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attribution': {
      id: '/admin/attribution'
      path: '/attribution'
      fullPath: '/admin/attribution'
      preLoaderRoute: typeof AdminAttributionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/influencers': {
      id: '/admin/influencers'
      path: '/influencers'
      fullPath: '/admin/influencers'
      preLoaderRoute: typeof AdminInfluencersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/influencer/': {
      id: '/influencer/'
      path: '/'
      fullPath: '/influencer/'
      preLoaderRoute: typeof InfluencerIndexRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/$page': {
      id: '/influencer/$page'
      path: '/$page'
      fullPath: '/influencer/$page'
      preLoaderRoute: typeof InfluencerPageRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/analytics': {
      id: '/influencer/analytics'
      path: '/analytics'
      fullPath: '/influencer/analytics'
      preLoaderRoute: typeof InfluencerAnalyticsRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/campaigns': {
      id: '/influencer/campaigns'
      path: '/campaigns'
      fullPath: '/influencer/campaigns'
      preLoaderRoute: typeof InfluencerCampaignsRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/dashboard': {
      id: '/influencer/dashboard'
      path: '/dashboard'
      fullPath: '/influencer/dashboard'
      preLoaderRoute: typeof InfluencerDashboardRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/discover': {
      id: '/influencer/discover'
      path: '/discover'
      fullPath: '/influencer/discover'
      preLoaderRoute: typeof InfluencerDiscoverRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/earnings': {
      id: '/influencer/earnings'
      path: '/earnings'
      fullPath: '/influencer/earnings'
      preLoaderRoute: typeof InfluencerEarningsRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/instagram-automation': {
      id: '/influencer/instagram-automation'
      path: '/instagram-automation'
      fullPath: '/influencer/instagram-automation'
      preLoaderRoute: typeof InfluencerInstagramAutomationRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/links': {
      id: '/influencer/links'
      path: '/links'
      fullPath: '/influencer/links'
      preLoaderRoute: typeof InfluencerLinksRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/notifications': {
      id: '/influencer/notifications'
      path: '/notifications'
      fullPath: '/influencer/notifications'
      preLoaderRoute: typeof InfluencerNotificationsRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/orders': {
      id: '/influencer/orders'
      path: '/orders'
      fullPath: '/influencer/orders'
      preLoaderRoute: typeof InfluencerOrdersRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/products': {
      id: '/influencer/products'
      path: '/products'
      fullPath: '/influencer/products'
      preLoaderRoute: typeof InfluencerProductsRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/profile': {
      id: '/influencer/profile'
      path: '/profile'
      fullPath: '/influencer/profile'
      preLoaderRoute: typeof InfluencerProfileRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/store': {
      id: '/influencer/store'
      path: '/store'
      fullPath: '/influencer/store'
      preLoaderRoute: typeof InfluencerStoreRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/influencer/support': {
      id: '/influencer/support'
      path: '/support'
      fullPath: '/influencer/support'
      preLoaderRoute: typeof InfluencerSupportRouteImport
      parentRoute: typeof InfluencerRoute
    }
    '/store-admin/': {
      id: '/store-admin/'
      path: '/'
      fullPath: '/store-admin/'
      preLoaderRoute: typeof StoreAdminIndexRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/$page': {
      id: '/store-admin/$page'
      path: '/$page'
      fullPath: '/store-admin/$page'
      preLoaderRoute: typeof StoreAdminPageRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/affiliate': {
      id: '/store-admin/affiliate'
      path: '/affiliate'
      fullPath: '/store-admin/affiliate'
      preLoaderRoute: typeof StoreAdminAffiliateRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/analytics': {
      id: '/store-admin/analytics'
      path: '/analytics'
      fullPath: '/store-admin/analytics'
      preLoaderRoute: typeof StoreAdminAnalyticsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/campaigns': {
      id: '/store-admin/campaigns'
      path: '/campaigns'
      fullPath: '/store-admin/campaigns'
      preLoaderRoute: typeof StoreAdminCampaignsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/commissions': {
      id: '/store-admin/commissions'
      path: '/commissions'
      fullPath: '/store-admin/commissions'
      preLoaderRoute: typeof StoreAdminCommissionsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/creators': {
      id: '/store-admin/creators'
      path: '/creators'
      fullPath: '/store-admin/creators'
      preLoaderRoute: typeof StoreAdminCreatorsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/customers': {
      id: '/store-admin/customers'
      path: '/customers'
      fullPath: '/store-admin/customers'
      preLoaderRoute: typeof StoreAdminCustomersRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/dashboard': {
      id: '/store-admin/dashboard'
      path: '/dashboard'
      fullPath: '/store-admin/dashboard'
      preLoaderRoute: typeof StoreAdminDashboardRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/discounts': {
      id: '/store-admin/discounts'
      path: '/discounts'
      fullPath: '/store-admin/discounts'
      preLoaderRoute: typeof StoreAdminDiscountsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/integrations': {
      id: '/store-admin/integrations'
      path: '/integrations'
      fullPath: '/store-admin/integrations'
      preLoaderRoute: typeof StoreAdminIntegrationsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/orders': {
      id: '/store-admin/orders'
      path: '/orders'
      fullPath: '/store-admin/orders'
      preLoaderRoute: typeof StoreAdminOrdersRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/products': {
      id: '/store-admin/products'
      path: '/products'
      fullPath: '/store-admin/products'
      preLoaderRoute: typeof StoreAdminProductsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/reports': {
      id: '/store-admin/reports'
      path: '/reports'
      fullPath: '/store-admin/reports'
      preLoaderRoute: typeof StoreAdminReportsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/settings': {
      id: '/store-admin/settings'
      path: '/settings'
      fullPath: '/store-admin/settings'
      preLoaderRoute: typeof StoreAdminSettingsRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store-admin/store': {
      id: '/store-admin/store'
      path: '/store'
      fullPath: '/store-admin/store'
      preLoaderRoute: typeof StoreAdminStoreRouteImport
      parentRoute: typeof StoreAdminRoute
    }
    '/store/login': {
      id: '/store/login'
      path: '/store/login'
      fullPath: '/store/login'
      preLoaderRoute: typeof StoreLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/influencers/': {
      id: '/admin/influencers/'
      path: '/'
      fullPath: '/admin/influencers/'
      preLoaderRoute: typeof AdminInfluencersIndexRouteImport
      parentRoute: typeof AdminInfluencersRoute
    }
    '/admin/influencers/$influencerId': {
      id: '/admin/influencers/$influencerId'
      path: '/$influencerId'
      fullPath: '/admin/influencers/$influencerId'
      preLoaderRoute: typeof AdminInfluencersInfluencerIdRouteImport
      parentRoute: typeof AdminInfluencersRoute
    }
    '/influencer/campaigns/': {
      id: '/influencer/campaigns/'
      path: '/'
      fullPath: '/influencer/campaigns/'
      preLoaderRoute: typeof InfluencerCampaignsIndexRouteImport
      parentRoute: typeof InfluencerCampaignsRoute
    }
    '/influencer/campaigns/$campaignId': {
      id: '/influencer/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/influencer/campaigns/$campaignId'
      preLoaderRoute: typeof InfluencerCampaignsCampaignIdRouteImport
      parentRoute: typeof InfluencerCampaignsRoute
    }
    '/influencer/instagram-automation/': {
      id: '/influencer/instagram-automation/'
      path: '/'
      fullPath: '/influencer/instagram-automation/'
      preLoaderRoute: typeof InfluencerInstagramAutomationIndexRouteImport
      parentRoute: typeof InfluencerInstagramAutomationRoute
    }
    '/store-admin/creators/': {
      id: '/store-admin/creators/'
      path: '/'
      fullPath: '/store-admin/creators/'
      preLoaderRoute: typeof StoreAdminCreatorsIndexRouteImport
      parentRoute: typeof StoreAdminCreatorsRoute
    }
    '/store-admin/creators/$creatorId': {
      id: '/store-admin/creators/$creatorId'
      path: '/$creatorId'
      fullPath: '/store-admin/creators/$creatorId'
      preLoaderRoute: typeof StoreAdminCreatorsCreatorIdRouteImport
      parentRoute: typeof StoreAdminCreatorsRoute
    }
    '/store-admin/orders/': {
      id: '/store-admin/orders/'
      path: '/'
      fullPath: '/store-admin/orders/'
      preLoaderRoute: typeof StoreAdminOrdersIndexRouteImport
      parentRoute: typeof StoreAdminOrdersRoute
    }
    '/store-admin/orders/$orderId': {
      id: '/store-admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/store-admin/orders/$orderId'
      preLoaderRoute: typeof StoreAdminOrdersOrderIdRouteImport
      parentRoute: typeof StoreAdminOrdersRoute
    }
    '/store-admin/products/': {
      id: '/store-admin/products/'
      path: '/'
      fullPath: '/store-admin/products/'
      preLoaderRoute: typeof StoreAdminProductsIndexRouteImport
      parentRoute: typeof StoreAdminProductsRoute
    }
    '/store-admin/products/$productId': {
      id: '/store-admin/products/$productId'
      path: '/$productId'
      fullPath: '/store-admin/products/$productId'
      preLoaderRoute: typeof StoreAdminProductsProductIdRouteImport
      parentRoute: typeof StoreAdminProductsRoute
    }
    '/influencer/instagram-automation/rules/$ruleId': {
      id: '/influencer/instagram-automation/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/influencer/instagram-automation/rules/$ruleId'
      preLoaderRoute: typeof InfluencerInstagramAutomationRulesRuleIdRouteImport
      parentRoute: typeof InfluencerInstagramAutomationRoute
    }
  }
}

interface AdminInfluencersRouteChildren {
  AdminInfluencersInfluencerIdRoute: typeof AdminInfluencersInfluencerIdRoute
  AdminInfluencersIndexRoute: typeof AdminInfluencersIndexRoute
}

const AdminInfluencersRouteChildren: AdminInfluencersRouteChildren = {
  AdminInfluencersInfluencerIdRoute: AdminInfluencersInfluencerIdRoute,
  AdminInfluencersIndexRoute: AdminInfluencersIndexRoute,
}

const AdminInfluencersRouteWithChildren =
  AdminInfluencersRoute._addFileChildren(AdminInfluencersRouteChildren)

interface AdminRouteChildren {
  AdminPageRoute: typeof AdminPageRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAttributionRoute: typeof AdminAttributionRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminInfluencersRoute: typeof AdminInfluencersRouteWithChildren
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPageRoute: AdminPageRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAttributionRoute: AdminAttributionRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminInfluencersRoute: AdminInfluencersRouteWithChildren,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InfluencerCampaignsRouteChildren {
  InfluencerCampaignsCampaignIdRoute: typeof InfluencerCampaignsCampaignIdRoute
  InfluencerCampaignsIndexRoute: typeof InfluencerCampaignsIndexRoute
}

const InfluencerCampaignsRouteChildren: InfluencerCampaignsRouteChildren = {
  InfluencerCampaignsCampaignIdRoute: InfluencerCampaignsCampaignIdRoute,
  InfluencerCampaignsIndexRoute: InfluencerCampaignsIndexRoute,
}

const InfluencerCampaignsRouteWithChildren =
  InfluencerCampaignsRoute._addFileChildren(InfluencerCampaignsRouteChildren)

interface InfluencerInstagramAutomationRouteChildren {
  InfluencerInstagramAutomationIndexRoute: typeof InfluencerInstagramAutomationIndexRoute
  InfluencerInstagramAutomationRulesRuleIdRoute: typeof InfluencerInstagramAutomationRulesRuleIdRoute
}

const InfluencerInstagramAutomationRouteChildren: InfluencerInstagramAutomationRouteChildren =
  {
    InfluencerInstagramAutomationIndexRoute:
      InfluencerInstagramAutomationIndexRoute,
    InfluencerInstagramAutomationRulesRuleIdRoute:
      InfluencerInstagramAutomationRulesRuleIdRoute,
  }

const InfluencerInstagramAutomationRouteWithChildren =
  InfluencerInstagramAutomationRoute._addFileChildren(
    InfluencerInstagramAutomationRouteChildren,
  )

interface InfluencerRouteChildren {
  InfluencerPageRoute: typeof InfluencerPageRoute
  InfluencerAnalyticsRoute: typeof InfluencerAnalyticsRoute
  InfluencerCampaignsRoute: typeof InfluencerCampaignsRouteWithChildren
  InfluencerDashboardRoute: typeof InfluencerDashboardRoute
  InfluencerDiscoverRoute: typeof InfluencerDiscoverRoute
  InfluencerEarningsRoute: typeof InfluencerEarningsRoute
  InfluencerInstagramAutomationRoute: typeof InfluencerInstagramAutomationRouteWithChildren
  InfluencerLinksRoute: typeof InfluencerLinksRoute
  InfluencerNotificationsRoute: typeof InfluencerNotificationsRoute
  InfluencerOrdersRoute: typeof InfluencerOrdersRoute
  InfluencerProductsRoute: typeof InfluencerProductsRoute
  InfluencerProfileRoute: typeof InfluencerProfileRoute
  InfluencerStoreRoute: typeof InfluencerStoreRoute
  InfluencerSupportRoute: typeof InfluencerSupportRoute
  InfluencerIndexRoute: typeof InfluencerIndexRoute
}

const InfluencerRouteChildren: InfluencerRouteChildren = {
  InfluencerPageRoute: InfluencerPageRoute,
  InfluencerAnalyticsRoute: InfluencerAnalyticsRoute,
  InfluencerCampaignsRoute: InfluencerCampaignsRouteWithChildren,
  InfluencerDashboardRoute: InfluencerDashboardRoute,
  InfluencerDiscoverRoute: InfluencerDiscoverRoute,
  InfluencerEarningsRoute: InfluencerEarningsRoute,
  InfluencerInstagramAutomationRoute:
    InfluencerInstagramAutomationRouteWithChildren,
  InfluencerLinksRoute: InfluencerLinksRoute,
  InfluencerNotificationsRoute: InfluencerNotificationsRoute,
  InfluencerOrdersRoute: InfluencerOrdersRoute,
  InfluencerProductsRoute: InfluencerProductsRoute,
  InfluencerProfileRoute: InfluencerProfileRoute,
  InfluencerStoreRoute: InfluencerStoreRoute,
  InfluencerSupportRoute: InfluencerSupportRoute,
  InfluencerIndexRoute: InfluencerIndexRoute,
}

const InfluencerRouteWithChildren = InfluencerRoute._addFileChildren(
  InfluencerRouteChildren,
)

interface StoreAdminCreatorsRouteChildren {
  StoreAdminCreatorsCreatorIdRoute: typeof StoreAdminCreatorsCreatorIdRoute
  StoreAdminCreatorsIndexRoute: typeof StoreAdminCreatorsIndexRoute
}

const StoreAdminCreatorsRouteChildren: StoreAdminCreatorsRouteChildren = {
  StoreAdminCreatorsCreatorIdRoute: StoreAdminCreatorsCreatorIdRoute,
  StoreAdminCreatorsIndexRoute: StoreAdminCreatorsIndexRoute,
}

const StoreAdminCreatorsRouteWithChildren =
  StoreAdminCreatorsRoute._addFileChildren(StoreAdminCreatorsRouteChildren)

interface StoreAdminOrdersRouteChildren {
  StoreAdminOrdersOrderIdRoute: typeof StoreAdminOrdersOrderIdRoute
  StoreAdminOrdersIndexRoute: typeof StoreAdminOrdersIndexRoute
}

const StoreAdminOrdersRouteChildren: StoreAdminOrdersRouteChildren = {
  StoreAdminOrdersOrderIdRoute: StoreAdminOrdersOrderIdRoute,
  StoreAdminOrdersIndexRoute: StoreAdminOrdersIndexRoute,
}

const StoreAdminOrdersRouteWithChildren =
  StoreAdminOrdersRoute._addFileChildren(StoreAdminOrdersRouteChildren)

interface StoreAdminProductsRouteChildren {
  StoreAdminProductsProductIdRoute: typeof StoreAdminProductsProductIdRoute
  StoreAdminProductsIndexRoute: typeof StoreAdminProductsIndexRoute
}

const StoreAdminProductsRouteChildren: StoreAdminProductsRouteChildren = {
  StoreAdminProductsProductIdRoute: StoreAdminProductsProductIdRoute,
  StoreAdminProductsIndexRoute: StoreAdminProductsIndexRoute,
}

const StoreAdminProductsRouteWithChildren =
  StoreAdminProductsRoute._addFileChildren(StoreAdminProductsRouteChildren)

interface StoreAdminRouteChildren {
  StoreAdminPageRoute: typeof StoreAdminPageRoute
  StoreAdminAffiliateRoute: typeof StoreAdminAffiliateRoute
  StoreAdminAnalyticsRoute: typeof StoreAdminAnalyticsRoute
  StoreAdminCampaignsRoute: typeof StoreAdminCampaignsRoute
  StoreAdminCommissionsRoute: typeof StoreAdminCommissionsRoute
  StoreAdminCreatorsRoute: typeof StoreAdminCreatorsRouteWithChildren
  StoreAdminCustomersRoute: typeof StoreAdminCustomersRoute
  StoreAdminDashboardRoute: typeof StoreAdminDashboardRoute
  StoreAdminDiscountsRoute: typeof StoreAdminDiscountsRoute
  StoreAdminIntegrationsRoute: typeof StoreAdminIntegrationsRoute
  StoreAdminOrdersRoute: typeof StoreAdminOrdersRouteWithChildren
  StoreAdminProductsRoute: typeof StoreAdminProductsRouteWithChildren
  StoreAdminReportsRoute: typeof StoreAdminReportsRoute
  StoreAdminSettingsRoute: typeof StoreAdminSettingsRoute
  StoreAdminStoreRoute: typeof StoreAdminStoreRoute
  StoreAdminIndexRoute: typeof StoreAdminIndexRoute
}

const StoreAdminRouteChildren: StoreAdminRouteChildren = {
  StoreAdminPageRoute: StoreAdminPageRoute,
  StoreAdminAffiliateRoute: StoreAdminAffiliateRoute,
  StoreAdminAnalyticsRoute: StoreAdminAnalyticsRoute,
  StoreAdminCampaignsRoute: StoreAdminCampaignsRoute,
  StoreAdminCommissionsRoute: StoreAdminCommissionsRoute,
  StoreAdminCreatorsRoute: StoreAdminCreatorsRouteWithChildren,
  StoreAdminCustomersRoute: StoreAdminCustomersRoute,
  StoreAdminDashboardRoute: StoreAdminDashboardRoute,
  StoreAdminDiscountsRoute: StoreAdminDiscountsRoute,
  StoreAdminIntegrationsRoute: StoreAdminIntegrationsRoute,
  StoreAdminOrdersRoute: StoreAdminOrdersRouteWithChildren,
  StoreAdminProductsRoute: StoreAdminProductsRouteWithChildren,
  StoreAdminReportsRoute: StoreAdminReportsRoute,
  StoreAdminSettingsRoute: StoreAdminSettingsRoute,
  StoreAdminStoreRoute: StoreAdminStoreRoute,
  StoreAdminIndexRoute: StoreAdminIndexRoute,
}

const StoreAdminRouteWithChildren = StoreAdminRoute._addFileChildren(
  StoreAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InfluencerRoute: InfluencerRouteWithChildren,
  LoginRoute: LoginRoute,
  StoreAdminRoute: StoreAdminRouteWithChildren,
  StoreLoginRoute: StoreLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
